[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "*"

before-test = "python -m pip install --upgrade setuptools pip wheel pytest"

#test-command = "tox -c {project}/tox.ini"
#test-requires = ["pytest","tox"]

test-command = "pytest {project}/tests"
test-requires = "pytest"

# Skip 32-bit builds
skip = ["*-win32", "*-manylinux_i686"]

# Disable building PyPy wheels on all platforms
skip = "pp*"
