[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "*"

before-test = "python -m pip install --upgrade setuptools pip wheel pytest"

#test-command = "tox -c {project}/tox.ini"
#test-requires = ["pytest","tox"]

test-command = "pytest {project}/tests"
test-requires = "pytest"

manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
#manylinux-ppc64le-image = "manylinux2014"
#manylinux-s390x-image = "manylinux2014"
#manylinux-pypy_x86_64-image = "manylinux2014"
#manylinux-pypy_i686-image = "manylinux2014"
#manylinux-pypy_aarch64-image = "manylinux2014"
