name: Build Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build ${{ matrix.build }}${{ matrix.arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            arch: "ARM64"
            build: ""
          - os: macos-12
            arch: "x86_64"
            build: ""

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for versioneer to find tags

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_ARCHS: "${{ matrix.arch }}"
          CIBW_BUILD: "cp39-${{ matrix.build }}*"
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_manylinux2010_wheels:
    name: Build ${{ matrix.arch }} manylinux2010 wheels
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: "x86_64"

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for versioneer to find tags

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_ARCHS: "${{ matrix.arch }}"
          CIBW_BUILD: "cp39-manylinux_*"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2010"
          CIBW_TEST_REQUIRES: pytest,tox
          CIBW_TEST_COMMAND: > 
                  pytest {project}/tests &&
                  tox -c {project}/tox.ini --workdir {package}/tests

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  check_dist:
    name: Check dist
    needs: [build_wheels, build_manylinux2010_wheels]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - run: pipx run twine check --strict dist/*

  # upload_pypi:
    # name: Upload to PyPI
    # needs: [check_dist]
    # runs-on: ubuntu-latest
    # if: github.event_name == 'push' && github.repository == 'scikit-build/cmake-python-distributions' && startsWith(github.ref, 'refs/tags/')
    # steps:
      # - uses: actions/download-artifact@v3
        # with:
          # name: artifact
          # path: dist

      # - name: Upload to PyPI
        # uses: pypa/gh-action-pypi-publish@v1.6.4
        # with:
          # password: ${{ secrets.PYPI_RELEASE_PASSWORD }}
